CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    surname    VARCHAR(70)                             NOT NULL,
    name       VARCHAR(70)                             NOT NULL,
    patronymic VARCHAR(70)                             NOT NULL,
    email      VARCHAR(30) UNIQUE                      NOT NULL,
    birthday   DATE                                    NOT NULL,
    phone      VARCHAR(11) UNIQUE                      NOT NULL,
    password   VARCHAR                                 NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email),
    CONSTRAINT UQ_USER_PHONE UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS cards
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id        BIGINT                                  NOT NULL,
    number          VARCHAR UNIQUE                          NOT NULL,
    issue_date      DATE                                    NOT NULL,
    expiration_date DATE                                    NOT NULL,
    cvv             VARCHAR                                 NOT NULL,
    opened          BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_card PRIMARY KEY (id),
    FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);
